services:
  ros-dash:
    build: .
    container_name: ros-dash
    network_mode: host
    volumes:
      - /var/snap/docker/common/ros-dash/users.json:/app/users.json
      - /var/snap/docker/common/ros-dash/ros-dash.db:/app/ros-dash.db
      - /var/snap/docker/common/ros-dash/oui-cache.json:/app/oui-cache.json
    restart: unless-stopped
